In [2]:
import numpy as np
import pandas as pd

In [6]:
falsy_values = (0, False, None, "",[],{})

In [7]:
any(falsy_values)

False

In [8]:
np.nan

nan

In [18]:
3+np.nan

nan

In [19]:
a = np.array([1,2,3,np.nan,np.nan,4])

In [20]:
a.sum()

nan

In [21]:
a.mean()

nan

In [23]:
float(3) + None

TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'

In [24]:
b = np.array([1,2,3,np.nan, None,4], dtype="float")
b

array([ 1.,  2.,  3., nan, nan,  4.])

In [25]:
b.sum()
b.mean()

nan

In [26]:
3 +np.inf

inf

In [27]:
np.inf/3

inf

In [29]:
np.inf/np.inf

nan

In [30]:
np.isnan(np.nan)

True

In [31]:
np.isinf(np.inf)

True

In [32]:
np.isfinite(np.nan), np.isfinite(np.inf)

(False, False)

In [33]:
np.isfinite(a)

array([ True,  True,  True, False, False,  True])

In [35]:
np.isfinite(b)

array([ True,  True,  True, False, False,  True])

In [36]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [38]:
# a[~np.isnan(a)] is same as:
a[np.isfinite(a)]

array([1., 2., 3., 4.])

In [39]:
#using the above, all operation can now be performed
a[np.isfinite(a)].mean()

2.5

In [40]:
a[np.isfinite(a)].sum()

10.0

**Pandas utility functions

In [41]:
pd.isnull(np.nan)

True

In [42]:
pd.isnull(None)

True

In [43]:
pd.isna(np.nan)

True

In [44]:
pd.isna(None)

True

In [45]:
pd.notnull(None)

False

In [46]:
pd.notnull(np.nan)

False

In [47]:
pd.notna(np.nan)

False

In [49]:
pd.notnull(3)

True

In [52]:
pd.notnull(a)

array([ True,  True,  True, False, False,  True])

In [53]:
a[pd.notnull(a)]

array([1., 2., 3., 4.])

In [55]:
c= np.array([1,np.nan,7])
pd.isnull(pd.Series([c]))

0    False
dtype: bool

In [56]:
pd.notnull(c)

array([ True, False,  True])

In [57]:
pd.isnull(c)

array([False,  True, False])

In [58]:
pd.notnull(pd.Series(c))

0     True
1    False
2     True
dtype: bool

In [59]:
pd.isnull(pd.Series(c))

0    False
1     True
2    False
dtype: bool

In [60]:
d = pd.DataFrame({'Column A':[1, np.nan,7],
                 'Column B':[np.nan, 2,3],
                 'Column C': [np.nan,2,np.nan]})

In [61]:
d

Column A  Column B  Column C
0       1.0       NaN       NaN
1       NaN       2.0       2.0
2       7.0       3.0       NaN

In [ ]:
pd.isnull(d)

In [63]:
pd.notnull(d)

Column A  Column B  Column C
0      True     False     False
1     False      True      True
2      True      True     False

In [66]:
np.isfinite(d)

Column A  Column B  Column C
0      True     False     False
1     False      True      True
2      True      True     False

*PANDAS OPERATION WITH MISSING VALUES

In [68]:
e=pd.Series([1,2,np.nan])
e.count()

2

In [69]:
e.mean()

1.5

In [70]:
e.sum()

3.0

In [75]:
e.shape

3

In [76]:
e.size

3

In [77]:
#Filtering the mising data
s = pd.Series([1,2,3,np.nan,np.nan,4])

In [78]:
pd.notnull(s)

0     True
1     True
2     True
3    False
4    False
5     True
dtype: bool

In [79]:
pd.isnull(s)

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [80]:
s.isnull()

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [82]:
s.notnull()

0     True
1     True
2     True
3    False
4    False
5     True
dtype: bool

In [83]:
s[s.notnull()]

0    1.0
1    2.0
2    3.0
5    4.0
dtype: float64

In [84]:
#dropping na values
s

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    4.0
dtype: float64

In [85]:
s.dropna()

0    1.0
1    2.0
2    3.0
5    4.0
dtype: float64

In [13]:
#dropping null values on dataframes
df = pd.DataFrame({
    'Column A': [1, np.nan, 30, np.nan],
    'Column B' :[2, 8, 31, np.nan],
    'Column C':[np.nan, 9, 32,100],
    'Column D' :[5,8,34,110]
})

In [4]:
df

Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [5]:
df.shape

(4, 4)

In [6]:
df.size

16

In [14]:
df.describe()

Column A   Column B    Column C    Column D
count   2.000000   3.000000    3.000000    4.000000
mean   15.500000  13.666667   47.000000   39.250000
std    20.506097  15.307950   47.318073   48.931074
min     1.000000   2.000000    9.000000    5.000000
25%     8.250000   5.000000   20.500000    7.250000
50%    15.500000   8.000000   32.000000   21.000000
75%    22.750000  19.500000   66.000000   53.000000
max    30.000000  31.000000  100.000000  110.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Column A  2 non-null      float64
 1   Column B  3 non-null      float64
 2   Column C  3 non-null      float64
 3   Column D  4 non-null      int64  
dtypes: float64(3), int64(1)
memory usage: 256.0 bytes


In [15]:
df.isnull()

Column A  Column B  Column C  Column D
0     False     False      True     False
1      True     False     False     False
2     False     False     False     False
3      True      True     False     False

In [16]:
df.notnull()

Column A  Column B  Column C  Column D
0      True      True     False      True
1     False      True      True      True
2      True      True      True      True
3     False     False      True      True

In [18]:
df.isnull().sum()

Column A    2
Column B    1
Column C    1
Column D    0
dtype: int64

In [19]:
df.dropna()

Column A  Column B  Column C  Column D
2      30.0      31.0      32.0        34

In [23]:
# df.dropna(axis=0) or
df.dropna(axis='rows')

Column A  Column B  Column C  Column D
2      30.0      31.0      32.0        34

In [21]:
# df.dropna(axis=1) or
df.dropna(axis='columns')

Column D
0         5
1         8
2        34
3       110

In [24]:
df2 = pd.DataFrame({
    'Column A': [1, np.nan, 30],
    'Column B': [2, np.nan, 31],
    'Column C': [np.nan, np.nan, 100]
})

In [27]:
df

Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [26]:
df.dropna(how='all')

Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [28]:
df.dropna(how='any') #default behavior

Column A  Column B  Column C  Column D
2      30.0      31.0      32.0        34

In [29]:
df

Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [30]:
df.dropna(thresh=3)

Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34

In [35]:
df.dropna(thresh=3, axis=1)

Column B  Column C  Column D
0       2.0       NaN         5
1       8.0       9.0         8
2      31.0      32.0        34
3       NaN     100.0       110

In [49]:
(df+df2)+9

Column A  Column B  Column C  Column D
0      11.0      13.0       NaN       NaN
1       NaN       NaN       NaN       NaN
2      69.0      71.0     141.0       NaN
3       NaN       NaN       NaN       NaN

*FILLING NULL VALUES*

In [52]:
s = pd.Series([1, 2, 3, np.nan, np.nan, 4])
s

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    4.0
dtype: float64

In [56]:
s.fillna(s.mean())

0    1.0
1    2.0
2    3.0
3    2.5
4    2.5
5    4.0
dtype: float64

In [57]:
s.fillna("LOLS")

0     1.0
1     2.0
2     3.0
3    LOLS
4    LOLS
5     4.0
dtype: object

In [59]:
s

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    4.0
dtype: float64

In [ ]:
#filling nulls with contiguous(close) values

In [60]:
s.fillna(method='ffill')

0    1.0
1    2.0
2    3.0
3    3.0
4    3.0
5    4.0
dtype: float64

In [61]:
s.fillna(method='bfill')

0    1.0
1    2.0
2    3.0
3    4.0
4    4.0
5    4.0
dtype: float64

In [63]:
pd.Series([np.nan, 3, np.nan, 9]).fillna(method='bfill')

0    3.0
1    3.0
2    9.0
3    9.0
dtype: float64

In [64]:
#on dataframes
df

Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [67]:
df.fillna({"Column A":0,'Column B':99,'Column C':df['Column C'].mean()})

Column A  Column B  Column C  Column D
0       1.0       2.0      47.0         5
1       0.0       8.0       9.0         8
2      30.0      31.0      32.0        34
3       0.0      99.0     100.0       110

In [72]:
df.fillna(method='bfill', axis =1)

Column A  Column B  Column C  Column D
0       1.0       2.0       5.0       5.0
1       8.0       8.0       9.0       8.0
2      30.0      31.0      32.0      34.0
3     100.0     100.0     100.0     110.0

In [73]:
#checking if there are NA
s.dropna().count()

4

In [74]:
missing_values = len(s.dropna()) != len(s)
missing_values

True

In [78]:
nas=len(s)-s.count()
nas

2

In [82]:
#more pythonic soln *any
pd.Series([True, False, False]).any()

True

In [84]:
pd.Series([False, False, False]).all()

False

In [85]:
s.isnull()

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [88]:
pd.Series([1,np.nan]).isnull().any()

True

In [89]:
s.isnull().any()

True

In [90]:
s.notnull().all()

False

In [92]:
s.fillna(method='ffill')

0    1.0
1    2.0
2    3.0
3    3.0
4    3.0
5    4.0
dtype: float64

In [93]:
s.isnull().values

array([False, False, False,  True,  True, False])

In [94]:
s.isnull().values.any()

True

**CLEANING NON NULL VALUE**

In [96]:
df = pd.DataFrame({
    'Sex': ['M', 'F', 'F', 'D', '?'],
    'Age': [29, 30, 24, 290, 25],
})
df

Sex  Age
0   M   29
1   F   30
2   F   24
3   D  290
4   ?   25

In [97]:
df['Sex'].unique()

array(['M', 'F', 'D', '?'], dtype=object)

In [98]:
df["Sex"].value_counts()

F    2
M    1
D    1
?    1
Name: Sex, dtype: int64

In [103]:
df['Sex'].replace({'D':'F','N':'M'})

0    M
1    F
2    F
3    F
4    ?
Name: Sex, dtype: object

In [104]:
df.replace({'Sex':{'D':'F','N':'M'},
           'Age':{290:90}
           })

Sex  Age
0   M   29
1   F   30
2   F   24
3   F   90
4   ?   25

In [105]:
df[df['Age']>100]

Sex  Age
3   D  290

In [109]:
df.loc[df['Age']>100,'Age'] = df.loc[df['Age']>100,'Age']/10
df

Sex   Age
0   M  29.0
1   F  30.0
2   F  24.0
3   D  29.0
4   ?  25.0

In [108]:
5/7

0.7142857142857143