In [1]:
import numpy as np

In [4]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.random.random((2,5))

array([[0.4009575 , 0.01340927, 0.21991741, 0.45470264, 0.96321563],
       [0.02745368, 0.92858646, 0.40561267, 0.34601137, 0.22598842]])

In [8]:
 s =np.arange(-3,4)

In [13]:
#3d arrays
array_1_2D = np.array([[1,2],[5,7]])
array_2_2D = np.array([[8,9],[5,7]])
array_3_2D = np.array([[1,2],[5,7]])
array_3D = np.array([array_1_2D,array_2_2D,array_3_2D])

In [15]:
array_3D.flatten()

array([1, 2, 5, 7, 8, 9, 5, 7, 1, 2, 5, 7])

In [19]:
array_3D.reshape((4,3))

array([[1, 2, 5],
       [7, 8, 9],
       [5, 7, 1],
       [2, 5, 7]])

In [20]:
# Create an array of zeros with three rows and two columns
zero_array = np.zeros((3, 2))

# Print the data type of zero_array
print(zero_array.dtype)

# Create a new array of int32 zeros with three rows and two columns
zero_int_array = np.zeros((3,2), dtype=np.int32)

# Print the data type of zero_int_array
print(zero_int_array.dtype)

float64
int32


In [ ]:
# Print the data type of sudoku_game
print(sudoku_game.dtype)

# Change the data type of sudoku_game to int8
small_sudoku_game = sudoku_game.astype(np.int8)

# Print the data type of small_sudoku_game
print(small_sudoku_game.dtype)

In [ ]:
# Create an array of trunk diameters with even row indices from 50 to 100 inclusive
every_other_diameter = tree_census[50:101:2,2]
print(every_other_diameter)

In [ ]:
# Extract trunk diameters information and sort from smallest to largest
sorted_trunk_diameters = np.sort(tree_census[:,2], axis=0)
print(sorted_trunk_diameters)