In [1]:
import numpy as np

In [4]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.random.random((2,5))

array([[0.4009575 , 0.01340927, 0.21991741, 0.45470264, 0.96321563],
       [0.02745368, 0.92858646, 0.40561267, 0.34601137, 0.22598842]])

In [8]:
 s =np.arange(-3,4)

In [13]:
#3d arrays
array_1_2D = np.array([[1,2],[5,7]])
array_2_2D = np.array([[8,9],[5,7]])
array_3_2D = np.array([[1,2],[5,7]])
array_3D = np.array([array_1_2D,array_2_2D,array_3_2D])

In [15]:
array_3D.flatten()

array([1, 2, 5, 7, 8, 9, 5, 7, 1, 2, 5, 7])

In [19]:
array_3D.reshape((4,3))

array([[1, 2, 5],
       [7, 8, 9],
       [5, 7, 1],
       [2, 5, 7]])