In [1]:
import numpy as np

In [4]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.random.random((2,5))

array([[0.4009575 , 0.01340927, 0.21991741, 0.45470264, 0.96321563],
       [0.02745368, 0.92858646, 0.40561267, 0.34601137, 0.22598842]])

In [8]:
 s =np.arange(-3,4)

In [13]:
#3d arrays
array_1_2D = np.array([[1,2],[5,7]])
array_2_2D = np.array([[8,9],[5,7]])
array_3_2D = np.array([[1,2],[5,7]])
array_3D = np.array([array_1_2D,array_2_2D,array_3_2D])

In [15]:
array_3D.flatten()

array([1, 2, 5, 7, 8, 9, 5, 7, 1, 2, 5, 7])

In [19]:
array_3D.reshape((4,3))

array([[1, 2, 5],
       [7, 8, 9],
       [5, 7, 1],
       [2, 5, 7]])

In [20]:
# Create an array of zeros with three rows and two columns
zero_array = np.zeros((3, 2))

# Print the data type of zero_array
print(zero_array.dtype)

# Create a new array of int32 zeros with three rows and two columns
zero_int_array = np.zeros((3,2), dtype=np.int32)

# Print the data type of zero_int_array
print(zero_int_array.dtype)

float64
int32


In [ ]:
# Print the data type of sudoku_game
print(sudoku_game.dtype)

# Change the data type of sudoku_game to int8
small_sudoku_game = sudoku_game.astype(np.int8)

# Print the data type of small_sudoku_game
print(small_sudoku_game.dtype)

In [ ]:
# Create an array of trunk diameters with even row indices from 50 to 100 inclusive
every_other_diameter = tree_census[50:101:2,2]
print(every_other_diameter)

In [ ]:
# Extract trunk diameters information and sort from smallest to largest
sorted_trunk_diameters = np.sort(tree_census[:,2], axis=0)
print(sorted_trunk_diameters)

In [2]:
import numpy as np
one_to_five = np.arange(1,6)
mask = one_to_five % 2 == 0
one_to_five[mask]

array([2, 4])

In [3]:
one2tousand = np.arange(1,1000)
mask = one2tousand % 3 == 0
div_by_3 = one2tousand[mask]

In [7]:
room_id_sizes = np.array([[1,22],[2,21],[3,27],[4,26]])
room_id_sizes

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26]])

In [10]:
room_id_sizes[:,0][room_id_sizes[:,1]%2==0]

array([1, 4])

In [11]:
#filtering with np.where
np.where(room_id_sizes[:,1]%2==0)

(array([0, 3]),)

In [12]:
sudoku = np.array([[5,3,0,0,7,0,0,0,0],
                    [6,0,0,1,9,5,0,0,0],
                    [0,9,8,0,0,0,0,6,0],
                    [8,0,0,0,6,0,0,0,3],
                    [4,0,0,8,0,3,0,0,1],
                    [7,0,0,0,2,0,0,0,6],
                    [0,6,0,0,0,0,2,8,0],
                    [0,0,0,4,1,9,0,0,5],
                    [0,0,0,0,8,0,0,7,9]])

In [14]:
row_ind, col_ind = np.where(sudoku == 0)
row_ind, col_ind

(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3,
        3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7,
        7, 8, 8, 8, 8, 8, 8]),
 array([2, 3, 5, 6, 7, 8, 1, 2, 6, 7, 8, 0, 3, 4, 5, 6, 8, 1, 2, 3, 5, 6,
        7, 1, 2, 4, 6, 7, 1, 2, 3, 5, 6, 7, 0, 2, 3, 4, 5, 8, 0, 1, 2, 6,
        7, 0, 1, 2, 3, 5, 6]))

In [23]:
#find and replace
sudoku_x = np.where(sudoku == 0,'999',sudoku)

In [25]:
np.where(sudoku_x == 2,"w",sudoku_x)

/var/folders/g6/qw3t2lbx7x91r1mfyp6k77k00000gn/T/ipykernel_9297/23362863.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  np.where(sudoku_x == 2,"w",sudoku_x)


array([['5', '3', '999', '999', '7', '999', '999', '999', '999'],
       ['6', '999', '999', '1', '9', '5', '999', '999', '999'],
       ['999', '9', '8', '999', '999', '999', '999', '6', '999'],
       ['8', '999', '999', '999', '6', '999', '999', '999', '3'],
       ['4', '999', '999', '8', '999', '3', '999', '999', '1'],
       ['7', '999', '999', '999', '2', '999', '999', '999', '6'],
       ['999', '6', '999', '999', '999', '999', '2', '8', '999'],
       ['999', '999', '999', '4', '1', '9', '999', '999', '5'],
       ['999', '999', '999', '999', '8', '999', '999', '7', '9']],
      dtype='<U21')

In [ ]:
# Create an array which contains row data on the largest tree in tree_census
largest_tree_data = tree_census[tree_census[:, 2] == 51]
print(largest_tree_data)

# Slice largest_tree_data to get only the block ID
largest_tree_block_id = largest_tree_data[:, 1]
print(largest_tree_block_id)

# Create an array which contains row data on all trees with largest_tree_block_id
trees_on_largest_tree_block = tree_census[tree_census[:, 1] == largest_tree_block_id]
print(trees_on_largest_tree_block)